### ISSUE TITLE
Torrent 검색엔진 API 찾아서  /movies/ api 만들기

### ISSUE THREAD

**Issue by sungyongcho** [woolimi/hypertube#27]
영화관련 정보 API: themoviedb
- https://developer.themoviedb.org/reference/discover-movie

API key
- 749c936af069d8c7366eb92fa5003461

API Access token

eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NDljOTM2YWYwNjlkOGM3MzY2ZWI5MmZhNTAwMzQ2MSIsInN1YiI6IjY1Y2UyYWY5YzI2Nzk2MDE3ZWM5M2E1NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.BuHZ9EYsPha8mCseFblsgupWjuhYpsJALlv7AB5-0Rc

**Comment by sungyongcho** [comment]
토렌트 검색 api
https://github.com/theriturajps/Torrent-Search-API

- all로 두고 검색하면 엄청 오래걸림
- 토렌트 서치엔진별 응답하는 파라미터 값들이 조금씩 다름



![Image](https://github.com/woolimi/hypertube/assets/46742040/ca5e9100-6f1c-4d98-b29c-ef23827eae6c)



![Image](https://github.com/woolimi/hypertube/assets/46742040/e47e5ab0-be26-428a-a8c8-34b020c7eabe)

**Comment by woolimi** [comment]
영화관련 정보 API workflow

1. TMDB API 의 populor 를 이용해서 TOP100 영화들의 목록을 가져온다 (language 설정). 이 영화의 목록에 있는 title, poster url 로 homepage 영화 리스트를 보여준다. (https://developer.themoviedb.org/reference/movie-popular-list)
2. 유저가 영화 포스터를 클릭하면 
  - DB에 영화정보가 없다? TMDB API 의 movie detail api 를 이용해서 해당 영화의 자세한 정보 + imdb 아이디를 우리 db 에 저장한다.
    (https://developer.themoviedb.org/reference/movie-details)
  - DB에 영화정보가 있다? DB에 있는 정보를 보여준다
3.  유저가 영화화면에서 영화보기를 클릭하면
  - 영화가 서버에 저장이 안되있다면?
     yts 에서 크롤링을 해서 토렌트와 자막을 받아온다.
     영화 스트림
  - 영화가 서버에 저장이 되어있다면
     영화를 바로 스트림

영화검색로직 
1. TMDB 에서 keyword 로 검색을 해옴 (https://developer.themoviedb.org/reference/search-movie), 영화포스터를 뿌려줌
2. 영화 포스터를 클릭하면 .... 위와 같이 작동함
