### ISSUE TITLE
클러스터에서 작동하는 Dockerizing Prod

### ISSUE THREAD

**Issue by woolimi** [woolimi/hypertube#57]

**Comment by sungyongcho** [comment]
docker-compose production 생성은 @jmcheon 님이,

학교에서 mysql db 생성이 안되는 문제는 @sungyongcho 가 내일 학교에서 테스트 해보기로 했습니다

**Comment by sungyongcho** [comment]
리소스: https://github.com/innercircle-byebye/ft_transcendence/tree/develop
